name: Build and Deploy Next.js with Sanity Studio

on:
  push:
    branches: ["master"]

jobs:
  deploy_sanity_studio:
    name: Build and Deploy Sanity Studio
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: skABUHvlwwRpim49YvGquK7QNCR7vdnRLvLWZ9FPsAxtWAthcHC2kfgUx54xifvqrmqdkbMaBDnGRywRYCqe050aFLDbsANMVjCBpqKf13ijDKZswEKOP1wR687FtxPHw0JiZhNSH9LvPem5EReZwEOJ5Ix3Jv0D8KPUn8xU37lL18c4gaRY

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js for Sanity Studio
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Restore cached Node Modules for Sanity Studio
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies for Sanity Studio
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Deploy Sanity Studio
        run: npm run deploy
        env:
          CI: true

  deploy_nextjs:
    name: Build and Deploy Next.js Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node.js for Next.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"  # Or the desired version for Next.js

      - name: Restore cache for Next.js
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies for Next.js
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: .next

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: nextjs-build
